import { jsPDF } from "jspdf";

export interface SIData {
  siNumber: string;
  projectName: string;
  siTo: string;
  shipper: string;
  consignee: string;
  consigneeAddress?: string;
  notifyParty: string;
  notifyPartyAddress?: string;
  quantity: number;
  nomination: string;
  loadingPort: string;
  dischargePort: string;
  laycan: string;
  shippingTerm: string;
  analysisMethod: string;
  goods: string;
  marked: string;
  specGar?: number;
  specNar?: number;
  specTs?: number;
  specAsh?: number;
  specTm?: number;
  specIm?: number;
  specVm?: number;
  specSize?: string;
}

export function generateShippingInstructionPDF(data: SIData): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const left = 54;
  const labelX = 54;
  const colonX = 236;
  const valueX = 246;
  const valueWidth = 290;

  doc.setProperties({ title: `Shipping Instruction - ${data.projectName}` });
  doc.setFont("helvetica");

  doc.setDrawColor(20, 57, 112);
  doc.setLineWidth(1.4);
  doc.line(36, 86, pageWidth - 36, 86);

  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("SHIPPING INSTRUCTION", pageWidth / 2, 106, { align: "center" });
  doc.setLineWidth(0.4);
  doc.line(pageWidth / 2 - 54, 108, pageWidth / 2 + 54, 108);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text(`NO.: ${data.siNumber}`, pageWidth / 2, 118, { align: "center" });

  let y = 143;
  const drawField = (label: string, value: string, emphasis = false) => {
    doc.setFont("helvetica", emphasis ? "bold" : "normal");
    doc.setFontSize(7.5);
    doc.text(label.toUpperCase(), labelX, y);
    doc.text(":", colonX, y);
    const lines = doc.splitTextToSize(value, valueWidth);
    doc.text(lines, valueX, y);
    y += Math.max(11, lines.length * 8.5 + 2);
  };

  doc.setFont("helvetica", "bold");
  doc.text("TO", labelX - 24, y);
  doc.text(":", labelX - 6, y);
  doc.text(data.siTo.toUpperCase(), labelX + 7, y);
  y += 23;

  const consigneeText = data.consigneeAddress 
    ? `${data.consignee.toUpperCase()}\n${data.consigneeAddress.toUpperCase()}` 
    : data.consignee.toUpperCase();
  const notifyPartyText = data.notifyPartyAddress 
    ? `${data.notifyParty.toUpperCase()}\n${data.notifyPartyAddress.toUpperCase()}` 
    : data.notifyParty.toUpperCase();

  drawField("Forecast Sales / From MV", data.projectName.toUpperCase(), true);
  drawField("Shipper", `${data.shipper.toUpperCase()}\nQQ PT. MAHAKARYA SENTRA ENERGI`);
  drawField("Consignee", consigneeText);
  drawField("Notify Party", notifyPartyText);
  y += 6;
  drawField("Shipping Term", data.shippingTerm.toUpperCase());
  drawField("Description of Goods", data.goods.toUpperCase());
  drawField("Quantity", `${data.quantity.toLocaleString()} MT (+/- 10%)`);
  drawField("Nomination", data.nomination.toUpperCase());
  drawField("Loading Port", data.loadingPort.toUpperCase());
  drawField("Discharge Port", data.dischargePort.toUpperCase());
  drawField("Laycan", data.laycan.toUpperCase());
  
  if (data.specGar || data.specTs || data.specAsh || data.specTm) {
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.text("COAL SPECIFICATION", labelX, y);
    y += 12;
    
    const specs: string[] = [];
    if (data.specGar) specs.push(`GAR: ${data.specGar} kcal/kg`);
    if (data.specNar) specs.push(`NAR: ${data.specNar} kcal/kg`);
    if (data.specTs) specs.push(`TS: ${data.specTs}%`);
    if (data.specAsh) specs.push(`ASH: ${data.specAsh}%`);
    if (data.specTm) specs.push(`TM: ${data.specTm}%`);
    if (data.specIm) specs.push(`IM: ${data.specIm}%`);
    if (data.specVm) specs.push(`VM: ${data.specVm}%`);
    if (data.specSize) specs.push(`SIZE: ${data.specSize}`);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    specs.forEach(spec => {
      doc.text(spec, valueX, y);
      y += 10;
    });
  }

  y += 8;
  drawField("Analysis Method", data.analysisMethod.toUpperCase());
  drawField("Marked", data.marked);

  y += 15;
  doc.setFontSize(6.5);
  doc.setTextColor(100);
  doc.text(`Generated by CoalTrade OS on ${new Date().toLocaleString()}`, pageWidth / 2, y, { align: "center" });

  return doc;
}
