"use client";

import { useState } from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api-client";

type DetailTab = "overview" | "operation" | "contract" | "royalty" | "invoice" | "documents" | "legal" | "freight" | "quality" | "communication";
type Workspace = {
  child: { id: string; nominationNumber: string; bargeName: string; tugBoatName: string | null; dwt: number | null; nominationDate: string | null; nominatedBy: string | null; loadingPort: string | null; laycanStart: string | null; laycanEnd: string | null; plannedQty: number | null; loadedQty: number | null; finalQty: number | null; tolerancePercent: number | null; lhvIssued: boolean; lhvIssuedDate: string | null; blDate: string | null; status: string; currentStage: string | null; source: string | null; supplier: string | null; notes: string | null; iupOp: string | null; contractNo: string | null; contractStatus: string | null; softcopyStatus: string | null; hardcopyStatus: string | null; opsApproval: string | null; qaApproval: string | null; legalApproval: string | null; royaltyBillingId: string | null; royaltyQty: number | null; royaltyAmount: number | null; invoiceCount: number | null; invoiceAmount: number | null; invoiceStatus: string | null; freightRate: number | null; allowance: number | null; demurrage: number | null; despatch: number | null; laytimeResult: string | null; pebStatus: string | null; legalStatus: string | null; qualityResult: unknown; communicationLog: unknown };
  parent: { shipmentNumber: string; vesselName: string | null; buyer: string };
  previousId: string | null;
  nextId: string | null;
  issues: { id: string; category: string; description: string; status: string }[];
  documents: { requirementCode: string; label: string; status: string; files: { id: string; originalName: string | null; publicUrl: string | null; visibility: string }[] }[];
  quality: { status: string; surveyor: string | null; samplingDate: string | null; warningNotes: string | null } | null;
  payments: { id: string; invoiceNumber: string | null; amount: number | null; status: string; dueDate: string | null }[];
  operations: { id: string; vesselName: string | null; bargeName: string | null; loadingPort: string | null; freightRate: number | null; allowance: number | null; demurrage: number | null; despatch: number | null; eta: string | null; status: string }[];
  summary: { planQty: number; actualQty: number; variance: number; variancePercent: number | null; tolerance: number; withinTolerance: boolean; documentCount: number; pendingDocuments: number };
};

const date = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) : "Not available";
const qty = (value: number | null | undefined) => value == null ? "Not available" : `${value.toLocaleString()} MT`;
const label = (value: string | null | undefined) => value ? value.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) : "Not available";

const stages = ["Allocation", "Contract", "Nomination", "Loading", "Documents", "Invoice", "Result"];
const tabs: [DetailTab, string][] = [
  ["overview", "Overview"], ["operation", "Operation"], ["contract", "Contract"], ["royalty", "Royalty"],
  ["invoice", "Invoice"], ["documents", "Documents (PEB)"], ["legal", "Legal Documents"],
  ["freight", "Freight & Laytime"], ["quality", "Quality Result"], ["communication", "Communication"],
];

export function BargeWorkspace({ parentId, childId }: { parentId: string; childId: string }) {
  const [active, setActive] = useState<DetailTab>("overview");
  const [editOpen, setEditOpen] = useState(false);
  const { data, isLoading, isError } = useQuery({
    queryKey: ["shipments", "child-workspace", parentId, childId],
    queryFn: () => api.get<{ data: Workspace }>(`/api/shipments/${parentId}/child-nominations/${childId}/workspace`),
  });
  if (isLoading) return <LoadingState />;
  if (isError || !data?.data) return <div className="card p-8 text-center text-muted-foreground">Barge line workspace unavailable.</div>;
  const workspace = data.data;
  const { child, parent, summary } = workspace;
  const currentStage = stages.findIndex((stage) => stage.toLowerCase().replaceAll(" ", "_") === child.currentStage);
  return <main className="mx-auto flex w-full max-w-[1440px] flex-col gap-5 pb-8">
    <header className="flex flex-wrap items-start justify-between gap-4">
      <div><p className="text-xs text-muted-foreground">Shipment Monitor › {parent.shipmentNumber} › {child.nominationNumber}</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold">Barge Line #{child.nominationNumber}</h1><span className="badge badge--warning">{label(child.currentStage ?? child.status)}</span></div><p className="mt-1 text-sm text-muted-foreground">{child.source ?? "Not available"} · {child.supplier ?? "Not available"} · Mother Vessel: {parent.vesselName ?? "Not available"}</p></div>
      <div className="flex flex-wrap gap-2"><Link href={`/shipment-monitor/${parentId}#children`} className="button button--sm button--ghost button--neutral">← Back to MV</Link>{workspace.previousId && <Link href={`/shipment-monitor/${parentId}/child/${workspace.previousId}`} className="button button--sm button--ghost button--neutral">‹ Previous</Link>}{workspace.nextId && <Link href={`/shipment-monitor/${parentId}/child/${workspace.nextId}`} className="button button--sm button--ghost button--neutral">Next ›</Link>}<button type="button" className="button button--sm button--primary" onClick={() => setEditOpen((value) => !value)}>{editOpen ? "Close Edit" : "Edit"}</button></div>
    </header>
    <InfoPanel rows={[["Source", child.source], ["Supplier / IUP", child.supplier], ["Jetty / Port", child.loadingPort], ["Barge", child.bargeName], ["Barge Laycan", `${date(child.laycanStart)} - ${date(child.laycanEnd)}`], ["Qty Plan", qty(child.plannedQty)], ["COB / Jetty Qty", qty(child.loadedQty)], ["BL Date", date(child.blDate)], ["Mother Vessel", parent.vesselName]]} />
    <nav className="flex gap-1 overflow-x-auto rounded-lg border border-border bg-surface p-1">{tabs.map(([key, text]) => <button key={key} type="button" className={`button button--xs flex-shrink-0 ${active === key ? "button--primary" : "button--ghost button--neutral"}`} onClick={() => setActive(key)} aria-pressed={active === key}>{text}</button>)}</nav>
    <div className="flex gap-2 overflow-x-auto border-b border-border pb-3">{stages.map((stage, index) => { const done = currentStage >= 0 && index < currentStage; const selected = index === currentStage; return <div key={stage} className="flex min-w-[100px] items-center gap-2 text-xs"><span className={`flex h-7 w-7 items-center justify-center rounded-full border font-semibold ${done ? "border-emerald-500 bg-emerald-50 text-emerald-700" : selected ? "border-amber-500 bg-amber-50 text-amber-700" : "border-border text-muted-foreground"}`}>{done ? "✓" : index + 1}</span><span className={selected ? "font-semibold text-amber-700" : "text-muted-foreground"}>{stage}<br /><small>{done ? "Done" : selected ? "In Progress" : "Pending"}</small></span></div>; })}</div>
    {editOpen && <ChildEdit parentId={parentId} child={child} />}
    {active === "overview" && <div className="grid grid-cols-1 gap-4 xl:grid-cols-4"><Info title="Source & Allocation" rows={[["Source", child.source], ["Supplier / IUP Holder", child.supplier], ["IUP OP", "Not available"], ["Jetty / Loading Port", child.loadingPort], ["Nominated By", child.nominatedBy]]} /><Info title="Barge & Status" rows={[["Tug Boat", child.tugBoatName], ["Barge", child.bargeName], ["DWT", child.dwt ? `${child.dwt.toLocaleString()} DWT` : null], ["Nomination Date", date(child.nominationDate)], ["Status", label(child.status)], ["Remarks", child.notes]]} /><Info title="Quantity Summary" rows={[["Plan Qty", qty(summary.planQty)], ["COB / Jetty Qty", qty(summary.actualQty)], ["Loss / Gain", `${summary.variance >= 0 ? "+" : ""}${summary.variance.toLocaleString()} MT`], ["Variance", summary.variancePercent == null ? "Not available" : `${summary.variancePercent >= 0 ? "+" : ""}${summary.variancePercent.toFixed(2)}%`], ["Tolerance", `±${summary.tolerance.toFixed(2)}%`], ["Result", summary.withinTolerance ? "Within Tolerance" : "Outside Tolerance"]]} /><Info title="Document & Invoice Alert" rows={[["Pending Documents", String(summary.pendingDocuments)], ["Attached Files", String(summary.documentCount)], ["LHV", child.lhvIssued ? `Issued ${date(child.lhvIssuedDate)}` : "Pending"], ["Invoice", "Not available"]]} /></div>}
    {active === "operation" && <Info title="Operation Progress" rows={[["Current Stage", label(child.currentStage)], ["Barge Laycan", `${date(child.laycanStart)} - ${date(child.laycanEnd)}`], ["LHV Issued", child.lhvIssued ? date(child.lhvIssuedDate) : "Pending"], ["BL Date", date(child.blDate)], ["ETA", date(null)]]} />}
    {active === "contract" && <Info title="Contract Status" rows={[["Source Contract", child.contractNo], ["Softcopy", child.softcopyStatus], ["Hardcopy", child.hardcopyStatus], ["Contract Status", child.contractStatus], ["Operations Approval", child.opsApproval], ["QA Approval", child.qaApproval], ["Legal Approval", child.legalApproval]]} />}
    {active === "royalty" && <Info title="Royalty" rows={[["Status", child.royaltyBillingId ? "Billed" : "Not available"], ["Billing ID", child.royaltyBillingId], ["Quantity", child.royaltyQty == null ? null : qty(child.royaltyQty)], ["Amount", child.royaltyAmount == null ? null : String(child.royaltyAmount)]]} />}
    {active === "invoice" && <Info title="Invoice Tracker" rows={[["Invoice Count", child.invoiceCount], ["Total Amount", child.invoiceAmount == null ? "Not available" : String(child.invoiceAmount)], ["Status", child.invoiceStatus]]} />}
    {(active === "documents" || active === "legal") && <Documents documents={workspace.documents} />}
    {active === "freight" && <Info title="Freight & Laytime" rows={[["Freight Rate", child.freightRate == null ? "Restricted" : String(child.freightRate)], ["Allowance", child.allowance == null ? "Not available" : String(child.allowance)], ["Laytime", child.laytimeResult], ["Demurrage", child.demurrage == null ? "Restricted" : String(child.demurrage)], ["Despatch", child.despatch == null ? "Restricted" : String(child.despatch)]]} />}
    {active === "quality" && <Info title="Quality Result" rows={[["Result", workspace.quality?.status], ["Surveyor", workspace.quality?.surveyor], ["Sampling Date", date(workspace.quality?.samplingDate)], ["Warning", workspace.quality?.warningNotes]]} />}
    {active === "communication" && <Issues issues={workspace.issues} />}
  </main>;
}

function LoadingState() { return <div className="space-y-4 animate-pulse"><div className="h-24 rounded bg-muted" /><div className="h-12 rounded bg-muted" /><div className="h-64 rounded bg-muted" /></div>; }
function InfoPanel({ rows }: { rows: [string, React.ReactNode][] }) { return <section className="card"><div className="card__body"><div className="grid grid-cols-2 gap-4 sm:grid-cols-4 xl:grid-cols-9">{rows.map(([key, value]) => <div key={key} className="min-w-0"><p className="text-[11px] text-muted-foreground">{key}</p><p className="mt-1 truncate text-sm font-medium">{value ?? "Not available"}</p></div>)}</div></div></section>; }
function Info({ title: heading, rows }: { title: string; rows: [string, React.ReactNode][] }) { return <section className="card"><div className="card__body gap-2"><h2 className="mb-2 font-semibold">{heading}</h2>{rows.map(([key, value]) => <div key={key} className="flex justify-between gap-3 border-b border-border py-2 text-sm last:border-0"><span className="text-muted-foreground">{key}</span><span className="max-w-[60%] truncate text-right font-medium">{value == null || value === "" ? "Not available" : value}</span></div>)}</div></section>; }
function Documents({ documents }: { documents: Workspace["documents"] }) { return <section className="card"><div className="card__body gap-3"><h2 className="font-semibold">Documents</h2>{documents.length ? documents.map((document) => <div key={document.requirementCode} className="flex items-center justify-between border-b border-border py-2 text-sm"><span>{document.label}</span><span className="badge badge--sm badge--neutral">{label(document.status)} · {document.files.length} file(s)</span></div>) : <p className="py-8 text-center text-sm text-muted-foreground">No document data available.</p>}</div></section>; }
function Issues({ issues }: { issues: Workspace["issues"] }) { return <section className="card"><div className="card__body gap-3"><h2 className="font-semibold text-red-700">Remarks & Issues</h2>{issues.length ? issues.map((issue) => <div key={issue.id} className="rounded border border-red-200 p-3 text-sm"><p className="font-medium">{issue.category}</p><p>{issue.description}</p><p className="mt-1 text-xs text-muted-foreground">{label(issue.status)}</p></div>) : <p className="py-8 text-center text-sm text-muted-foreground">No active issues.</p>}</div></section>; }
function PaymentInfo({ payments }: { payments: Workspace["payments"] }) { return <section className="card"><div className="card__body gap-3"><h2 className="font-semibold">Invoice Tracker</h2>{payments.length ? <div className="overflow-x-auto"><table className="table w-full text-sm"><thead><tr><th>Invoice</th><th>Amount</th><th>Due</th><th>Status</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td>{payment.invoiceNumber ?? "Not available"}</td><td>{payment.amount == null ? "Not available" : `$${payment.amount.toLocaleString()}`}</td><td>{date(payment.dueDate)}</td><td>{label(payment.status)}</td></tr>)}</tbody></table></div> : <p className="py-8 text-center text-sm text-muted-foreground">Invoice data not available.</p>}</div></section>; }
function ChildEdit({ parentId, child }: { parentId: string; child: Workspace["child"] }) { const [loadedQty, setLoadedQty] = useState(String(child.loadedQty ?? "")); const [status, setStatus] = useState(child.status); const [stage, setStage] = useState(child.currentStage ?? "allocation"); const [message, setMessage] = useState<string | null>(null); const [pending, setPending] = useState(false); async function save(event: React.FormEvent) { event.preventDefault(); setPending(true); setMessage(null); const response = await fetch(`/api/shipments/${parentId}/child-nominations/${child.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ loadedQty: loadedQty || undefined, status, currentStage: stage }) }); setPending(false); if (!response.ok) { const body = await response.json().catch(() => ({})); setMessage(body.error ?? "Update failed"); return; } window.location.reload(); } return <form onSubmit={save} className="card border-primary/30"><div className="card__body grid grid-cols-1 gap-3 sm:grid-cols-4"><label className="field"><span className="field__label">Loaded Qty (MT)</span><input className="input" type="number" min="0" step="0.01" value={loadedQty} onChange={(event) => setLoadedQty(event.target.value)} /></label><label className="field"><span className="field__label">Status</span><select className="select" value={status} onChange={(event) => setStatus(event.target.value)}><option>planned</option><option>active</option><option>completed</option><option>cancelled</option></select></label><label className="field"><span className="field__label">Current Stage</span><select className="select" value={stage} onChange={(event) => setStage(event.target.value)}>{["allocation", "contract", "nomination", "standby_loading_port", "loading", "sailing_to_loading_port", "documents", "invoice", "settlement", "result"].map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><button className="button button--primary self-end" disabled={pending}>{pending ? "Saving..." : "Save Changes"}</button>{message && <p className="text-xs text-red-600 sm:col-span-4">{message}</p>}</div></form>; }
